namespace StepCodeDotNet.Interop;

public enum Op_Code
{
    OP_AND,
    OP_ANDOR,
    OP_ARRAY_ELEMENT,
    OP_CONCAT,
    OP_DIV,
    OP_DOT,
    OP_EQUAL,
    OP_EXP,
    OP_GREATER_EQUAL,
    OP_GREATER_THAN,
    OP_GROUP,
    OP_IN,
    OP_INST_EQUAL,
    OP_INST_NOT_EQUAL,
    OP_LESS_EQUAL,
    OP_LESS_THAN,
    OP_LIKE,
    OP_MINUS,
    OP_MOD,
    OP_NEGATE,
    OP_NOT,
    OP_NOT_EQUAL,
    OP_OR,
    OP_PLUS,
    OP_REAL_DIV,
    OP_SUBCOMPONENT,
    OP_TIMES,
    OP_XOR,
    OP_UNKNOWN,
    OP_LAST,
}
